name: Test on Tag

on:
  push:
    tags:
      - 'v*'
    

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: Echo Tag Name
          run: echo Tag Pushed to ${{ github.ref }}
