name: Test on Tag

on:
  push:
    tags:
      - 'Platform_v[0-9].[0-9]+.[0-9]+_[0-9]+'    

jobs:
    test:
        runs-on: ubuntu-latest
        steps:

        - name: Set Environment using Tag Name
          run: |
            export TAG_NAME=$(echo ${{ github.ref }} | sed -e 's/refs\/tags\///g')

        - name: Echo Tag Name
          run: echo Tag Pushed to ${TAG_NAME}
