name: Jest Tests

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'Message'
        required: true
        default: 'String Value'
        
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Send Slack Notification
      uses: archive/github-actions-slack@v2.8.0
      with:
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_TOKEN }}
        slack-channel: C05RF4QQ07L
        slack-text: Hola Mundo! ${{ github.event.inputs.test }}
        slack-optional-icon_emoji: ":fire:"
    
    
    
