name: Jest Tests

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'Test'
        required: true
        default: 'true'
      selected-option:
        description: 'Selected option'
        required: true
        type: choice
        options:
        - '1'
        - '2'
        - '3'
        - '4'
        - '5'
      boolean:
        type: boolean
        description: 'Boleano'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Run Jest tests
      run: npm test
