name: Test on Tag

on:
  push:
    tags:
      - 'Platform_v[0-9].[0-9]+.[0-9]+_[0-9]+'    

jobs:
    test:
        runs-on: ubuntu-latest
        steps:

        - name: Echo Tag Name
          run: echo Tag Pushed to ${{ github.ref }}
