name: Jest Tests

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'Test'
        required: true
        default: 'String Value'
      selected-option:
        description: 'Selected option'
        required: true
        type: choice
        options:
        - '1'
        - '2'
        - '3'
        - '4'
        - '5'
      boolean:
        type: boolean
        description: 'Boleano'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Send Slack Notification
      uses: archive/github-actions-slack@v2.8.0
      with:
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_TOKEN }}
        slack-channel: C05RF4QQ07L
        slack-text: Hola Mundo!
    
    
    
