name: Test on Tag

on:
  push:
    tags:
      - 'Platform_v[0-9].[0-9]+.[0-9]+_[0-9]+'    

jobs:
    test:
        runs-on: ubuntu-latest
        steps:

        - name: Echo Tag Name
          env:
            TAG_NAME: echo ${{ github.ref }} | sed 's/refs\/tags\///g'
          run: echo Tag Pushed to ${{ env.TAG_NAME }}
